"""
React Flow Output Models - Post-processed models for @xyflow/react frontend.
These are COMPUTED from the clean LLM Diagram — never generated by the LLM.
Contains ALL React Flow features: subflows, markers, z-index, interaction flags, etc.
"""
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


# ============================================================================
# 1. HANDLE CONFIG - Tells frontend where connection points live
# ============================================================================

class HandleConfig(BaseModel):
    """Describes a single connection handle on a node."""
    id: str = Field(description="Unique handle identifier (e.g. 'right', 'bottom-true').")
    type: Literal["source", "target"] = Field(description="Handle direction.")
    position: Literal["top", "right", "bottom", "left"] = Field(description="Edge of the node this handle sits on.")
    x: float = Field(default=0.5, description="Relative X position (0-1) on the node edge.")
    y: float = Field(default=0.5, description="Relative Y position (0-1) on the node edge.")


# ============================================================================
# 2. NODE OUTPUT - Full React Flow Node with all fields
# ============================================================================

Position = Literal["top", "right", "bottom", "left"]


class ReactFlowNodeOutput(BaseModel):
    """Complete node for @xyflow/react — LLM data + computed rendering info.

    Maps to React Flow's Node type:
    https://reactflow.dev/api-reference/types/node
    """
    id: str
    type: str
    position: Dict[str, float] = Field(default_factory=lambda: {"x": 0, "y": 0})
    data: Dict[str, Any]

    # Subflows / grouping
    parentId: Optional[str] = Field(default=None, description="Parent node id for subflows.")
    extent: Optional[Literal["parent"]] = Field(default=None, description="'parent' confines node to parent bounds.")
    expandParent: bool = Field(default=False, description="Auto-expand parent when child dragged to edge.")

    # Interaction flags
    draggable: bool = Field(default=True)
    selectable: bool = Field(default=True)
    deletable: bool = Field(default=True)
    focusable: bool = Field(default=False)
    hidden: bool = Field(default=False)

    # Z-index / stacking
    zIndex: int = Field(default=0, description="Computed stacking order (boundary=0, swimlane=1, system=10, actor=20).")

    # Styling
    style: Optional[Dict[str, Any]] = None
    className: Optional[str] = Field(default=None, description="Computed CSS class (e.g. 'rf-group--c4 rf-node--actor').")
    ariaLabel: Optional[str] = None

    # Handle positions
    sourcePosition: Optional[Position] = Field(default=None, description="Global source handle side (from layout direction).")
    targetPosition: Optional[Position] = Field(default=None, description="Global target handle side (from layout direction).")

    # Origin (default top-left)
    origin: List[float] = Field(default_factory=lambda: [0.0, 0.0], description="Node origin: [0,0]=top-left, [0.5,0.5]=center.")


# ============================================================================
# 3. EDGE OUTPUT - Full React Flow Edge with markers, labels, paths
# ============================================================================

class ReactFlowEdgeOutput(BaseModel):
    """Complete edge for @xyflow/react — LLM data + computed rendering info.

    Maps to React Flow's Edge type:
    https://reactflow.dev/api-reference/types/edge
    """
    id: str
    source: str
    target: str
    sourceHandle: Optional[str] = None
    targetHandle: Optional[str] = None

    # Edge type determines path rendering
    type: str = Field(default="default", description="'default' (bezier), 'smoothstep', 'step', 'straight'.")

    # Animation
    animated: bool = Field(default=False, description="Computed from logic_variant — non-standard flows animate.")

    # Arrow markers
    markerEnd: Optional[Dict[str, Any]] = Field(default=None, description="Arrow marker at the end of the edge.")
    markerStart: Optional[Dict[str, Any]] = Field(default=None, description="Arrow marker at the start (for bidirectional).")

    # Path options
    pathOptions: Optional[Dict[str, Any]] = Field(default=None, description="e.g. {'curvature': 0.5} for bezier, {'offset': 20} for smoothstep.")

    # Label
    label: str = ""
    labelStyle: Optional[Dict[str, Any]] = None
    labelShowBg: bool = True
    labelBgStyle: Optional[Dict[str, Any]] = None
    labelBgPadding: Optional[List[float]] = None
    labelBgBorderRadius: Optional[float] = None

    # Data payload
    data: Dict[str, Any]

    # Interaction
    interactionWidth: int = Field(default=20, description="Invisible path width for easier clicking.")
    hidden: bool = False
    deletable: bool = True
    selectable: bool = True
    focusable: bool = False

    # Z-index / styling
    zIndex: int = 0
    style: Optional[Dict[str, Any]] = None
    className: Optional[str] = None


# ============================================================================
# 4. DIAGRAM OUTPUT - The final payload for the frontend
# ============================================================================

class ReactFlowDiagramOutput(BaseModel):
    """Complete post-processed diagram ready for @xyflow/react."""
    nodes: List[ReactFlowNodeOutput]
    edges: List[ReactFlowEdgeOutput]
    metadata: Dict[str, Any]
